In [1]:
import numpy as np
import pandas as pd

# ---- NumPy ----
temps = np.array([28.5, 31.2, 29.8, 33.0, 30.4, 27.9, 32.1])
print("Temperatures:", temps)
print("Average     :", round(temps.mean(), 2))
print("Hottest/Coolest:", temps.max(), "/", temps.min())
print("In Fahrenheit:", temps * 9 / 5 + 32)
print("Days above 30:", temps[temps > 30])
print("Last three days:", temps[-3:])
print("Reversed:", temps[::-1])

Temperatures: [28.5 31.2 29.8 33.  30.4 27.9 32.1]
Average     : 30.41
Hottest/Coolest: 33.0 / 27.9
In Fahrenheit: [83.3  88.16 85.64 91.4  86.72 82.22 89.78]
Days above 30: [31.2 33.  30.4 32.1]
Last three days: [30.4 27.9 32.1]
Reversed: [32.1 27.9 30.4 33.  29.8 31.2 28.5]


In [2]:
sales = np.arange(1, 13).reshape(3, 4) * 10
print("Weekly sales (3 shops x 4 weeks):\n", sales)
print("Shop-wise total :", sales.sum(axis=1))
print("Week-wise mean  :", sales.mean(axis=0))
print("Middle row      :", sales[1])
print("Last column     :", sales[:, -1])
print("Sub-block:\n", sales[0:2, 1:3])
print("Transpose shape :", sales.T.shape)

Weekly sales (3 shops x 4 weeks):
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
Shop-wise total : [100 260 420]
Week-wise mean  : [50. 60. 70. 80.]
Middle row      : [50 60 70 80]
Last column     : [ 40  80 120]
Sub-block:
 [[20 30]
 [60 70]]
Transpose shape : (4, 3)


In [3]:
# ---- Pandas ----
orders = pd.DataFrame({
    "Customer": ["Meena", "Raj", "Sunil", "Divya", "Karan"],
    "City":     ["Mysuru", "Bengaluru", "Mysuru", "Mandya", "Bengaluru"],
    "Amount":   [450, 820, 230, 610, 975],
    "Items":    [3, 5, 2, 4, 6],
})
print(orders, "\n")

print("Shape:", orders.shape)
print("Row 3 using loc :", orders.loc[3, "Customer"])
print("Rows 1-3 using iloc:\n", orders.iloc[1:4, 0:3])

orders["PerItem"] = (orders["Amount"] / orders["Items"]).round(1)
print("\nSorted by Amount (high to low):\n", orders.sort_values("Amount", ascending=False))
print("\nOrders above 500 from Bengaluru:\n", orders[(orders["Amount"] > 500) & (orders["City"] == "Bengaluru")])
print("\nCity-wise average amount:\n", orders.groupby("City")["Amount"].mean())

  Customer       City  Amount  Items
0    Meena     Mysuru     450      3
1      Raj  Bengaluru     820      5
2    Sunil     Mysuru     230      2
3    Divya     Mandya     610      4
4    Karan  Bengaluru     975      6 

Shape: (5, 4)
Row 3 using loc : Divya
Rows 1-3 using iloc:
   Customer       City  Amount
1      Raj  Bengaluru     820
2    Sunil     Mysuru     230
3    Divya     Mandya     610

Sorted by Amount (high to low):
   Customer       City  Amount  Items  PerItem
4    Karan  Bengaluru     975      6    162.5
1      Raj  Bengaluru     820      5    164.0
3    Divya     Mandya     610      4    152.5
0    Meena     Mysuru     450      3    150.0
2    Sunil     Mysuru     230      2    115.0

Orders above 500 from Bengaluru:
   Customer       City  Amount  Items  PerItem
1      Raj  Bengaluru     820      5    164.0
4    Karan  Bengaluru     975      6    162.5

City-wise average amount:
 City
Bengaluru    897.5
Mandya       610.0
Mysuru       340.0
Name: Amount, dtype: fl